version: '3.8'

services:
  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:5000

  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    networks:
      - app-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MongoDb=mongodb://mongo:27017/mydatabase

  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    networks:
      - app-network
    environment:
      MONGO_INITDB_DATABASE: UserDb

networks:
  app-network:
    driver: bridge
